# Generated by Django 3.0.3 on 2020-02-25 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_auto_20200225_1834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='pic',
            field=models.ImageField(blank=True, upload_to='media'),
        ),
    ]
