# Generated by Django 3.0.3 on 2020-02-25 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_auto_20200225_1849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='pic',
            field=models.FileField(upload_to=''),
        ),
    ]
