# Generated by Django 3.0.3 on 2020-02-27 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_auto_20200226_0653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='picurl',
            field=models.FileField(upload_to=''),
        ),
    ]
