# Generated by Django 3.0.3 on 2020-03-17 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_manager_uname'),
    ]

    operations = [
        migrations.AddField(
            model_name='manager',
            name='ip',
            field=models.CharField(default='', max_length=250),
        ),
    ]
