# Generated by Django 3.0.3 on 2020-03-17 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0003_manager_ip'),
    ]

    operations = [
        migrations.AddField(
            model_name='manager',
            name='country',
            field=models.CharField(default='', max_length=250),
        ),
    ]
