# Generated by Django 3.0.3 on 2020-02-15 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20200215_1721'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='test',
            new_name='article',
        ),
    ]
