# Generated by Django 3.0.3 on 2020-02-19 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_remove_article_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='fb',
            field=models.CharField(default='-', max_length=250),
        ),
        migrations.AddField(
            model_name='article',
            name='ph',
            field=models.CharField(default='-', max_length=250),
        ),
        migrations.AddField(
            model_name='article',
            name='tw',
            field=models.CharField(default='-', max_length=250),
        ),
        migrations.AddField(
            model_name='article',
            name='yt',
            field=models.CharField(default='-', max_length=250),
        ),
    ]
