# Generated by Django 3.0.3 on 2020-02-20 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_auto_20200219_0813'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='ints',
            field=models.CharField(default='-', max_length=250),
        ),
    ]
