# Generated by Django 3.0.3 on 2020-03-03 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_remove_article_ints'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='picname',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='article',
            name='picurl',
            field=models.TextField(default=''),
        ),
    ]
