# Generated by Django 3.0.3 on 2020-03-04 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_auto_20200303_0908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='picname',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='article',
            name='picurl',
            field=models.FileField(upload_to=''),
        ),
    ]
