# Generated by Django 3.0.3 on 2020-03-04 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_auto_20200304_0541'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='picname2',
            field=models.FileField(default='-', upload_to=''),
        ),
        migrations.AddField(
            model_name='article',
            name='picurl2',
            field=models.FileField(default='-', upload_to=''),
        ),
    ]
