# Generated by Django 3.0.3 on 2020-03-07 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_auto_20200304_1906'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='bodylong',
            field=models.TextField(default='-'),
        ),
    ]
