# Generated by Django 3.0.3 on 2020-03-31 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_article_bodylong'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='seokeywords',
            field=models.CharField(default='-', max_length=250),
        ),
        migrations.AddField(
            model_name='article',
            name='seotxt',
            field=models.CharField(default='-', max_length=250),
        ),
    ]
